remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: air
locale: vi-VN
title: Blog của Khanh
title_separator: '-'
name: Lê Phương Khanh
description: An amazing website.
url: 'https://khanhlp315.github.io'
baseurl: null
repository: khanhlp315/khanhlp315.github.io
teaser: null
words_per_minute: 200
comments:
  provider: facebook
  disqus:
    shortname: null
  discourse:
    server: null
  facebook:
    appid: '177907876225383'
    num_posts: null
    colorscheme: null
staticman:
  allowedFields: null
  branch: null
  commitMessage: null
  filename: null
  format: null
  moderation: null
  path: null
  requiredFields: null
  transforms:
    email: null
  generatedFields:
    date:
      type: null
      options:
        format: null
reCaptcha:
  siteKey: null
  secret: null
atom_feed:
  path: null
search: true
search_full_content: 'false'
search_provider: lunr
algolia:
  application_id: 'null'
  index_name: null
  search_only_api_key: null
  powered_by: null
google:
  search_engine_id: 'null'
  instant_search: null
google_site_verification: null
bing_site_verification: null
yandex_site_verification: null
naver_site_verification: null
twitter:
  username: null
facebook:
  username: khanhlp315
  app_id: null
  publisher: null
og_image: null
social:
  type: null
  name: null
  links:
    - 'https://facebook.com/khanhlp315'
analytics:
  provider: false
  google:
    tracking_id: null
    anonymize_ip: null
author:
  name: Lê Phương Khanh
  avatar: /images/avatar.jpg
  bio: .
  location: Thành phố Hồ Chí Minh
  email: khanhlp315@gmail.com
  uri: 'https://khanhlp315.github.io/'
  home: null
  bitbucket: null
  codepen: null
  dribbble: null
  flickr: null
  facebook: khanhlp315
  foursquare: null
  github: khanhlp315
  gitlab: null
  google_plus: null
  keybase: null
  instagram: null
  lastfm: null
  linkedin: null
  pinterest: null
  soundcloud: null
  stackoverflow: null
  steam: null
  tumblr: null
  twitter: null
  vine: null
  weibo: null
  xing: null
  youtube: null
include:
  - .htaccess
  - _pages
exclude:
  - '*.sublime-project'
  - '*.sublime-workspace'
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: utf-8
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: |+


incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: '/:categories/:title/'
paginate: 5
paginate_path: '/page:num/'
timezone: Asia/Ho_Chi_Minh
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: '/categories/:name/'
    tag: '/tags/:name/'
compress_html:
  clippings: all
  ignore:
    envs: development
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: 'true'
      share: true
      related: true
